### ISSUE TITLE
Add new sport

### ISSUE THREAD

**Issue by DavidHenryThoreau** [SamR1/FitTrackee#466] opened 2023-12-14 07:54 UTC
Can you let user add new sport, (example musculation) ?

**Comment by SamR1** [comment] 2023-12-16 10:58
Hi,

For now it's not possible for users to add their own sports.

---
duplicate of https://github.com/SamR1/FitTrackee/issues/364
additional comment on https://github.com/SamR1/FitTrackee/issues/391#issuecomment-1636681079

**Closed by SamR1** 2023-12-16 10:58 UTC

**Comment by DavidHenryThoreau** [comment] 2023-12-18 08:06
I've insert a new line in sport table :
```
fittrackee=# INSERT INTO sports (id,label,is_active,stopped_speed_threshold) VALUES (17,'Muscle Strengthening',true,0.1);
INSERT 0 1
```

**Comment by DavidHenryThoreau** [comment] 2024-05-28 08:42
I've insert a new line in sport table :
```
fittrackee=# INSERT INTO sports (id,label,is_active,stopped_speed_threshold) VALUES (55,'Renforcement',true,0.1);
INSERT 0 1

fittrackee=# select * from sports where id=55;
 id |    label     | is_active | stopped_speed_threshold
----+--------------+-----------+-------------------------
 55 | Renforcement | t         |                     0.1
(1 row)
```

In the web interface in the importing new workout page I'm getting :
`sport.Renforcement.value` how can I rename to 'Muscle Strengthening' as it's in the database ?
Is that a good way to create new sport directly in the database like this ?

**Comment by DavidHenryThoreau** [comment] 2024-05-28 08:45
I've inserted a new line in sport table :
```
fittrackee=# INSERT INTO sports (id,label,is_active,stopped_speed_threshold) VALUES (55,'Renforcement',true,0.1);
INSERT 0 1

fittrackee=# select * from sports where id=55;
 id |    label     | is_active | stopped_speed_threshold
----+--------------+-----------+-------------------------
 55 | Renforcement | t         |                     0.1
(1 row)
```

In the web interface in the importing new workout page I'm getting :
`sport.Renforcement.value` how can I rename to 'Renforcement' as it's in the database ?
Is that a good way to create new sport directly in the database like this ?

**Comment by SamR1** [comment] 2024-05-29 18:55
Hi,

It's not possible to create sports only in the database (see https://github.com/SamR1/FitTrackee/issues/364#issuecomment-1566160797).
