### ISSUE TITLE
follow equipment usage

### ISSUE THREAD

**Issue by DavidHenryThoreau** [SamR1/FitTrackee#460] opened 2023-11-27 14:22 UTC
It'd be nice to add equipment like shoes brand, or bike maybe a blank tag that user can add and set to each outdoor activities.

**Comment by SamR1** [comment] 2023-12-13 14:46
Duplicate of https://github.com/SamR1/FitTrackee/issues/259

A PR is already open, and I plan to work on it after the social features due to many changes.

**Closed by SamR1** 2023-12-13 14:46 UTC
