### ISSUE TITLE
weather data for uploads in past

### ISSUE THREAD

**Issue by speefak** [SamR1/FitTrackee#503] opened 2024-03-02 17:38 UTC
Hi, i configured the weather data now but the weather data, is noch updated for uploads in past. 

Is there a feature for already uploaded GPX files to update the weather data?

**Comment by SamR1** [comment] 2024-03-02 18:26
Hi,

for now, it's not possible to update weather data.

---

duplicate of https://github.com/SamR1/FitTrackee/issues/480

**Closed by SamR1** 2024-03-02 18:26 UTC
