### ISSUE TITLE
[feature] enable dark mode for desktop size

### ISSUE THREAD

**Issue by ballinger** [SamR1/FitTrackee#419] opened 2023-08-24 06:12 UTC
let the user switch to dark mode for desktop browsers.

**Comment by Thovi98** [comment] 2023-08-24 06:36
See https://github.com/SamR1/FitTrackee/issues/113

**Comment by ballinger** [comment] 2023-08-24 16:12
yeah i saw that, but i also see a dark mode when i browse the site on my mobile.. which also would be nice for desktop browsers :)

**Comment by SamR1** [comment] 2023-12-17 11:12
duplicate of #113

**Closed by SamR1** 2023-12-17 11:12 UTC
