### ISSUE TITLE
Development: Hot-reload in docker?

### ISSUE THREAD

**Issue by Fmstrat** [SamR1/FitTrackee#97] opened 2021-10-13 21:43 UTC
Hi,

I'm trying to get my development environment setup. I have a commit (https://github.com/Fmstrat/FitTrackee/commit/c2edfc9de442daafdd2069cddc7bf0b6564bf525) that gets everything in place for local development inside of docker which enables hot reloading in Flask, however I can't seem to figure out how to get React to hot reload as well. For instance, if I change a file, like `AdminUsers.jsx` React/Flask don't hot reload. But if I change `__main__.py`, Flask does.

I have found https://ajhyndman.medium.com/hot-reloading-with-react-and-flask-b5dae60d9898, but I'm not familiar enough with Flask/React combo to get this working.

Any ideas?

Thanks!

**Comment by SamR1** [comment] 2021-10-16 08:45
Hi,

The provided docker is only for application evaluation purpose, not for development.
Client part with dev tools (`fittrackee_client` directory) is not included (I don't use docker for FitTrackee development, not for deployment).

I can search how to include that part.

**Comment by SamR1** [comment] 2021-11-03 20:05
I'm closing this issue, since I'm not reproducing the error.

Feel free to reopen it, if needed.

**Closed by SamR1** 2021-11-03 20:05 UTC
Labels: enhancement, v0.4.x, development
