### ISSUE TITLE
Missing Sports

### ISSUE THREAD

**Issue by speefak** [SamR1/FitTrackee#501] opened 2024-02-28 09:04 UTC
Edit Sports is not possible, so i can only choose the given sports. Editing Value like Sports or the GPX Data would be nice ;)

**Comment by SamR1** [comment] 2024-03-02 06:51
Hi,

For now it's not possible for users to add their own sports.

---
duplicate of https://github.com/SamR1/FitTrackee/issues/364
additional comment on https://github.com/SamR1/FitTrackee/issues/391#issuecomment-1636681079

**Closed by SamR1** 2024-03-02 06:51 UTC
